@host=http://localhost:3000

### Including sample dashboards
POST {{host}}/dashboards/include


### Incluir NOVO Folder
POST {{host}}/dashboards
content-type: application/json

{
    "name": "Teste Pasta",
    "alias": "TS PT",
    "type": "FOLDER"
}

# folderParentId?: string
# embbededLink?: string

### Getting all dashboards
GET {{host}}/dashboards

### Getting dashboards by name (like)
GET {{host}}/dashboards?name=Ope

### Getting sorted by name
GET {{host}}/dashboards?sort=name,desc

### Getting sorted by name
GET {{host}}/dashboards?sort=name&sort=createdAt,desc

### Getting dashboards by folderParentId (equal)
GET {{host}}/dashboards?name=dash&sort=type&folderParentId=

### Getting AccessContent by id
GET {{host}}/dashboards/access/a17403c9-68a9-4cc4-99cf-108a59c8973f

### Getting Item Content by Id
GET {{host}}/dashboards/8bc658ff-3997-4001-89b2-955046365042
