@host=http://localhost:3000

### Including sample folders
POST {{host}}/folders/include


### Getting all folders
GET {{host}}/folders

### Getting folders by name (like)
GET {{host}}/folders?name=Ope

### Getting sorted by name
GET {{host}}/folders?sort=name,desc

### Getting sorted by name
GET {{host}}/folders?sort=name&sort=createdAt,desc

### Getting folders by folderParentId (equal)
GET {{host}}/folders?folderParentId=1a0e0f47-7a3a-400f-81c3-73486a5660e6
